import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Main from "./main";
import { ThemeProvider } from "@/contexts/ThemeContext";

// Use the Google Font (Archivo)
const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo", // Use a custom variable name if needed
});

const walone = localFont({
  src: "../../src/app/fonts/Z06-Walone-Bold.ttf",
  display: "swap",
  variable: "--font-z06-walone",
});

export const metadata: Metadata = {
  title: "Archivo Dev Space",
  description: "Generated by Archivo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${walone.variable} ${archivo.variable}`}>
      <body>
        <ThemeProvider>
          <Main>{children}</Main>
        </ThemeProvider>
      </body>
    </html>
  );
}
